version: '3.7'

services:
  serenity:
    image: gitlab.hatfieldfx.com:9005/dev/serenity:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3030:3030
    env_file:
      - .env
  db:
    image: postgres:9.6.20-alpine
    env_file:
      - .env
