version: '3.7'

services:
  serenity:
    image: gitlab.hatfieldfx.com:9005/dev/serenity:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5000:3030
    links:
      - serenity-db
    env_file:
      - .env
    environment:
      - NEO4J_HOST=bolt://serenity-db:7687

  serenity-db:
    image: neo4j:4.2.2
    ports:
      - 7474:7474  # http
      - 7687:7687  # bolt
    env_file:
      - .env
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PSWD}
